# Generated by Django 5.2.7 on 2025-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('WORK', 'Work'), ('EDUCATION', 'Education')], default='PERSONAL', max_length=20),
        ),
    ]
