# Generated by Django 5.2.7 on 2025-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='New Entry', max_length=100),
        ),
    ]
